# Generated by Django 2.1.1 on 2018-09-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20180906_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='student_id',
            new_name='student',
        ),
    ]
