# Generated by Django 2.1.1 on 2018-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='image_path',
            field=models.FilePathField(default='/home/jenish/Documents/FaceRecognition/media/', path='/home/jenish/Documents/FaceRecognition/media/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
