# Generated by Django 2.1.1 on 2018-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_auto_20180907_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
    ]
