# Generated by Django 2.1.1 on 2018-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_auto_20180907_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_path',
            field=models.FilePathField(default='/home/jenish/Documents/FaceRecognition/media/', path='/home/jenish/Documents/FaceRecognition/media/'),
        ),
    ]
