# Generated by Django 2.1.1 on 2018-09-09 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0015_auto_20180909_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(12, 19, 31, 175501)),
        ),
    ]
