# Generated by Django 2.1.1 on 2018-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0016_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
